- id: switch_on_apple_tv
  alias: Switch on the AppleTV
  trigger:
  - entity_id: media_player.apple_tv
    platform: state
    to: playing
  condition: []
  action:
  - service: script.switch_on_apple_tv
- id: '1544058608572'
  alias: Go to sleep on weekdays
  trigger:
  - at: 00:30:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: climate.heater
      temperature: 20
    service: climate.set_temperature
- id: '1544058656379'
  alias: Wake up
  trigger:
  - event_data:
      entity_id: timer.alarm_clock
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data:
      entity_id: climate.heater
      temperature: 22
    service: climate.set_temperature
  - data:
      entity_id: light.nightstand
      profile: reading
      transition: 900
    service: light.turn_on
- id: '1544639167076'
  alias: Leaving home
  trigger:
  - entity_id: group.presence
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: climate.heater
      temperature: 19
    service: climate.set_temperature
  - data:
      message: Itterasshai!
    service: notify.ios_vladimir_eremins_iphone
  - data:
      entity_id: switch.20820045bcddc2272725
    service: switch.turn_off
- id: '1544645154540'
  alias: Coming home
  trigger:
  - entity_id: group.presence
    from: not_home
    platform: state
    to: home
  condition:
  - after: 08:00:00
    before: 0:30:00
    condition: time
  action:
  - data:
      entity_id: climate.heater
      temperature: 20
    service: climate.set_temperature
  - data:
      message: Okaeri!
    service: notify.ios_vladimir_eremins_iphone
- id: '1558391222511'
  alias: Lights for TV
  trigger:
  - entity_id: media_player.hdmi_0
    from: 'on'
    platform: state
  condition: []
  action:
  - data:
      entity_id: light.living_room
      profile: reading
      transition: 15
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.living_room
      profile: reading
      transition: 14
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.living_room
      profile: reading
      transition: 13
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.living_room
      profile: reading
      transition: 12
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.living_room
      profile: reading
      transition: 11
    service: light.turn_on
  - delay: 00:00:01
  - data:
      entity_id: light.living_room
      profile: reading
      transition: 10
    service: light.turn_on
- id: '1560093057776'
  alias: Google Home Alarm
  trigger:
  - entity_id: sensor.bedroom_speaker_alarm
    from: unavailable
    platform: state
  condition:
  - condition: template
    value_template: '{{ states.sensor.bedroom_speaker_alarm.state != "unavailable"
      }}'
  action:
  - data:
      entity_id: switch.alarm_clock
    service: switch.turn_off
  - data:
      entity_id: switch.alarm_clock
    service: switch.turn_on
- id: '1560095818967'
  alias: Google Home Cancel Alarm
  trigger:
  - entity_id: sensor.bedroom_speaker_alarm
    platform: state
    to: unavailable
  condition:
  - condition: state
    entity_id: sensor.bedroom_speaker_alarm
    state: unavailable
  action:
  - data:
      entity_id: switch.alarm_clock
    service: switch.turn_off
- id: '1560863627264'
  alias: Heat shot
  trigger:
  - above: 21.9
    entity_id: climate.heater
    value_template: '{{ state.attributes.temperature }}'
    platform: numeric_state
  condition: []
  action:
  - delay: 00:30:00
  - data:
      entity_id: climate.heater
      temperature: 20
    service: climate.set_temperature
- id: '1563839668700'
  alias: Soundbar Volume
  trigger:
  - event_data: {}
    event_type: ir_command_received
    platform: event
  condition: []
  action:
  - service: shell_command.send_jvc_command
    data_template:
      button: '{{ trigger.event.data["button_name"] }}'
