- id: switch_on_apple_tv
  alias: Switch on the AppleTV
  trigger:
  - entity_id: media_player.apple_tv
    platform: state
    to: playing
  condition: []
  action:
  - service: script.switch_on_apple_tv
- id: '1544058608572'
  alias: Go to sleep on weekdays
  trigger:
  - at: 00:30:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      away_mode: true
      entity_id: climate.heater
    service: climate.set_away_mode
  - data:
      entity_id: climate.heater
      temperature: 20
    service: climate.set_temperature
- id: '1544058656379'
  alias: Wake up on weekdays
  trigger:
  - at: '8:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      away_mode: false
      entity_id: climate.heater
    service: climate.set_away_mode
  - data:
      entity_id: climate.heater
      temperature: 21
    service: climate.set_temperature
- id: '1544639167076'
  alias: Leaving home
  trigger:
  - entity_id: group.presence
    from: home
    platform: state
    to: not_home
  condition:
  - after: 08:00:00
    before: 00:30:00
    condition: time
  action:
  - data:
      away_mode: true
      entity_id: climate.heater
    service: climate.set_away_mode
  - data:
      entity_id: climate.heater
      temperature: 20
    service: climate.set_temperature
  - data:
      message: Itterasshai!
    service: notify.ios_vladimir_eremins_iphone
- id: '1544645154540'
  alias: Coming home
  trigger:
  - entity_id: group.presence
    from: not_home
    platform: state
    to: home
  condition:
  - after: 08:00:00
    before: 0:30:00
    condition: time
  action:
  - data:
      away_mode: false
      entity_id: climate.heater
    service: climate.set_away_mode
  - data:
      entity_id: climate.heater
      temperature: 21
    service: climate.set_temperature
  - data:
      message: Okaeri!
    service: notify.ios_vladimir_eremins_iphone
- id: '1544922225207'
  alias: Wake up on weekends
  trigger:
  - at: '10:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - data:
      away_mode: false
      entity_id: climate.heater
    service: climate.set_away_mode
  - data:
      entity_id: climate.heater
      temperature: 21
    service: climate.set_temperature
