esphomeyaml:
  esphomelib_version:
    branch: dev
  name: climate
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  power_save_mode: light
  manual_ip:
    static_ip: 192.168.1.237
    subnet: 255.255.255.0
    gateway: 192.168.1.1
    dns1: 192.168.1.1
    dns2: 8.8.8.8

ota:
  password: !secret ota
  safe_mode: False

logger:
  baud_rate: 115200

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/London

mqtt:
  broker: 192.168.1.110
  port: 1883
  username: homeassistant
  password: !secret mosquitto

sensor:
  - platform: wifi_signal
    name: "Climate WiFi Signal"
    update_interval: 10s
    expire_after: 120s
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          send_every: 6
          window_size: 12
  - platform: dht
    model: AM2302
    pin:
      number: 2
      mode: INPUT_PULLUP
    temperature:
      name: "Climate Temperature"
      accuracy_decimals: 2
      expire_after: 120s
      filters:
        - sliding_window_moving_average:
            send_every: 3
            window_size: 6
        - offset: -1.95
    humidity:
      name: "Climate Humidity"
      expire_after: 120s
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            send_every: 3
            window_size: 6
    update_interval: 20s
