homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  - type: legacy_api_password

zone:
  - name: Facebook London
    latitude: 51.516750365184734
    longitude: -0.13420922853739234
    icon: mdi:facebook-workplace
    radius: 250

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://home.yottatsa.name
  api_password: !secret http_password
  ssl_key: /etc/letsencrypt/live/home.yottatsa.name/privkey.pem
  ssl_certificate: /etc/letsencrypt/live/home.yottatsa.name/fullchain.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_interval: 1
  purge_keep_days: 7
  db_url: sqlite:////dev/shm/home-assistant_v2.db
  include:
    domains:
      - climate
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_humidity
      - sensor.living_room_temperature
      - sensor.living_room_temperature_filtered
      - sensor.living_room_humidity
      - sensor.bedroom_temperature
      - sensor.bedroom_light_level
      - sensor.bedroom_motion_sensor
      - binary_sensor.livingroom_motion_sensor
      - sensor.printed_pages
      - sensor.cpu_thermal_zone_0
      - sensor.disk_use_percent_
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.home_to_facebook_london
      - sensor.home_to_lsbu
      - sensor.brightbox2_kbytesec_received
      - sensor.brightbox2_kbytesec_sent
      - device_tracker.vladimir_eremins_iphone
      - sensor.keenetics
      - sensor.vladimir_eremins_iphone
      - sensor.heater
      - sensor.heater_wifi_signal_sensor
      - switch.heater

history:

logbook:
  include: {}

map:

sun:

mqtt:
  broker: 127.0.0.1
  discovery: True
  username: homeassistant
  password: !secret mosquitto

discovery:
  ignore:
    - philips_hue
  enable:
#    - dlna_dmr

sensor:
  - platform: dht
    sensor: AM2302
    name: Living Room
    pin: 24
    monitored_conditions:
      - temperature
      - humidity
    temperature_offset: -1.05
  - platform: filter
    name: living_room_temperature_filtered
    entity_id: sensor.living_room_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
  - platform: hue
    ip_address: 192.168.1.5
    token: !secret token
  - platform: template
    sensors:
      bedroom_temperature:
        friendly_name: 'Bedroom Temperature'
        value_template: '{{states.sensor.bedroom_motion_sensor.attributes.temperature}}'
        unit_of_measurement: °C
      bedroom_light_level:
        friendly_name: 'Bedroom light level'
        value_template: '{{states.sensor.bedroom_motion_sensor.attributes.lx}}'
        unit_of_measurement: lux
      printed_pages:
        friendly_name: 'Printed Pages'
        value_template: '{{states.sensor.hp_laserjet_professional_m1212nf_mfp.attributes.get("1.3.6.1.2.1.43.10.2.1.4.1.1") | int }}'
      temperature:
        friendly_name: 'Temperature'
        value_template: >
          {{ states("sensor.living_room_temperature_filtered") | float * 0.7 +
             states.sensor.bedroom_motion_sensor.attributes.temperature * 0.3 }}
        unit_of_measurement: °C
  - platform: command_line
    name: CPU Thermal Zone 0
    unit_of_measurement: °C
    alias: cpu_thermal_zone_0
    command: "cat /sys/devices/virtual/thermal/thermal_zone0/temp"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
  - platform: google_travel_time
    name: Home to Facebook London
    api_key: !secret google
    origin: zone.home
    destination: zone.facebook_london
    options:
      mode: transit
      transit_routing_preference: fewer_transfers
  - platform: google_travel_time
    name: Home to LSBU
    api_key: !secret google
    origin: zone.home
    destination: "103 Borough Road, London SE1 0AA"
    options:
      mode: transit
      transit_routing_preference: fewer_transfers
  - platform: darksky
    api_key: !secret api_key
    monitored_conditions:
      - temperature
      - humidity
      - minutely_summary
  - platform: history_stats
    name: Heater
    entity_id: switch.heater
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

switch:
  - platform: template
    switches:
      tv:
        friendly_name: "TV"
        value_template: "{{ is_state('switch.hdmi_0', 'on') }}"
        turn_on:
          service: script.switch_on_apple_tv
        turn_off:
          service: hdmi_cec.standby

nipca:

tts:
  - platform: google

# cloud:

upnp:

zeroconf:

ios:

homekit:
  filter:
    include_entities:
      - sensor.living_room_humidity
      - switch.tv
      - climate.heater

media_player:
  - platform: philips_js
    host: 192.168.1.6
    turn_on_action:
      service: script.switch_on_apple_tv

light:
  - platform: ambilights
    host: 192.168.1.6

logger:
  default: warn

apple_tv:
  - host: 192.168.1.246
    login_id: !secret pyatv_loginid
    credentials: !secret pyatv_credentials

climate:
  - platform: generic_thermostat
    name: Heater
    heater: switch.heater
    target_sensor: sensor.temperature
    min_temp: 15
    max_temp: 25
    ac_mode: False
    target_temp: 21
    min_cycle_duration: 
      minutes: 25
    cold_tolerance: 0.3
    hot_tolerance: 0.2
    precision: 0.1
    initial_operation_mode: auto
    away_temp: 20

hdmi_cec:
  osd_name: Pi
  devices:
    Philips TV: 0.0.0.0
    Apple TV: 1.0.0.0
    Pi: 2.0.0.0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
