homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant

zone:
  - name: Facebook London
    latitude: 51.516750365184734
    longitude: -0.13420922853739234
    icon: mdi:facebook-workplace
    radius: 250

frontend:

config:

http:
  base_url: https://home.yottatsa.name
  ssl_key: /etc/letsencrypt/live/home.yottatsa.name/privkey.pem
  ssl_certificate: /etc/letsencrypt/live/home.yottatsa.name/fullchain.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

conversation:

recorder:
  purge_interval: 1
  purge_keep_days: 1
  db_url: sqlite:////dev/shm/home-assistant_v2.db
  include:
    domains:
      - climate
      - device_tracker
      - proximity
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_humidity
      - sensor.bedroom_temperature
      - sensor.bedroom_sensor_temperature
      - sensor.bedroom_light_level
      - sensor.living_room_temperature_filtered
      - sensor.living_room_temperature
      - sensor.living_room_humidity
      - sensor.heater_wifi_signal
      - sensor.climate_wifi_signal
      - sensor.climate_temperature
      - sensor.climate_humidity
      - binary_sensor.bedroom_motion_sensor
      - binary_sensor.livingroom_motion_sensor
      - sensor.printed_pages
      - sensor.cpu_thermal_zone_0
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.home_to_facebook_london
      - sensor.home_to_lsbu
      - sensor.heater
      - sensor.heater_wifi_signal_sensor
      - switch.heater
      - binary_sensor.rpi_power_status

history:

logbook:
  include: {}

map:

sun:

mqtt:
  broker: 127.0.0.1
  discovery: True
  username: homeassistant
  password: !secret mosquitto

discovery:
  ignore:
    - igd
  enable:
#    - dlna_dmr

sensor:
  - platform: dht
    sensor: AM2302
    name: Living Room
    pin: 24
    monitored_conditions:
      - temperature
      - humidity
    temperature_offset: -0.95
  - platform: filter
    name: living_room_temperature_filtered
    entity_id: sensor.living_room_temperature
    filters:
      - filter: outlier
        window_size: 4 
        radius: 2.0
  - platform: template
    sensors:
      bedroom_sensor_temperature:
        friendly_name: 'Bedroom Sensor Temperature'
        value_template: "{{ state_attr('binary_sensor.bedroom_motion_sensor', 'temperature') }}"
        unit_of_measurement: °C
      bedroom_light_level:
        friendly_name: 'Bedroom Light Level'
        value_template: "{{ state_attr('binary_sensor.bedroom_motion_sensor', 'lx') }}"
        unit_of_measurement: lux
      printed_pages:
        friendly_name: 'Printed'
        value_template: "{{ (state_attr('sensor.hp_laserjet_professional_m1212nf_mfp', '1.3.6.1.2.1.43.10.2.1.4.1.1') | int) or None }}"
        unit_of_measurement: pages
      temperature:
        friendly_name: 'Temperature'
        value_template: >
          {{ (is_state('timer.alarm_clock', 'active') and
          states.sensor.climate_temperature.state | float or
          states.sensor.living_room_temperature_filtered.state | float or
          states.sensor.living_room_temperature_filtered.state | float
          )}}
        unit_of_measurement: °C
  - platform: command_line
    name: CPU Thermal Zone 0
    unit_of_measurement: °C
    alias: cpu_thermal_zone_0
    command: "cat /sys/devices/virtual/thermal/thermal_zone0/temp"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
  - platform: google_travel_time
    name: Home to Facebook London
    api_key: !secret google
    origin: zone.home
    destination: zone.facebook_london
    options:
      mode: transit
      transit_routing_preference: fewer_transfers
  - platform: google_travel_time
    name: Home to LSBU
    api_key: !secret google
    origin: zone.home
    destination: "103 Borough Road, London SE1 0AA"
    options:
      mode: transit
      transit_routing_preference: fewer_transfers
  - platform: darksky
    api_key: !secret api_key
    monitored_conditions:
      - temperature
      - humidity
      - minutely_summary
  - platform: history_stats
    name: Heater
    entity_id: switch.heater
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

binary_sensor:
  - platform: rpi_power
  - platform: sdnotify
  - platform: hue
  - platform: workday
    country: UK
    workdays: [mon, tue, wed, thu, fri]

switch:
  - platform: template
    switches:
      tv:
        friendly_name: "TV"
        value_template: "{{ is_state('switch.hdmi_0', 'on') }}"
        turn_on:
          service: script.switch_on_apple_tv
        turn_off:
          service: hdmi_cec.standby
      alarm_clock:
        friendly_name: "Alarm Clock"
        value_template: "{{ is_state('timer.alarm_clock', 'active') }}"
        turn_on:
          service: timer.start
          data:
            entity_id: timer.alarm_clock
        turn_off:
          service: timer.cancel
          data:
            entity_id: timer.alarm_clock

nipca:

tts:
  - platform: google

# cloud:

zeroconf:

ios:

homekit:
  filter:
    include_entities:
      - sensor.living_room_humidity
      - switch.tv
      - climate.heater
      - switch.alarm_clock
      - sensor.climate_temperature

media_player:
#  - platform: philips_js
#    host: 192.168.1.6
#    turn_on_action:
#      service: script.switch_on_apple_tv

light:
#  - platform: ambilights
#    host: 192.168.1.6

logger:
  default: warn
  logs:
    custom_components.binary_sensor.hue: debug
    custom_components.sensor.hue: debug
    urllib3: error
    #custom_components.device_tracker: debug
    #homeassistant.components.switch.hdmi_cec: debug
    #homeassistant.components.hdmi_cec: debug
    #pycec: info

apple_tv:
  - host: 192.168.1.246
    login_id: !secret pyatv_loginid
    credentials: !secret pyatv_credentials

climate:
  - platform: generic_thermostat
    name: Heater
    heater: switch.heater
    target_sensor: sensor.temperature
    min_temp: 15
    max_temp: 25
    ac_mode: False
    min_cycle_duration: 
      minutes: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.2
    keep_alive:
      minutes: 1
    precision: 0.1
    initial_operation_mode: auto

hdmi_cec:
  osd_name: raspberry
  devices:
    Philips TV: 0.0.0.0
    Apple TV: 1.0.0.0
    Pi: 2.0.0.0

device_tracker:
  - platform: hue
    interval_seconds: 60

proximity:
  home:
    zone: home
    devices:
      - device_tracker.vladimir_eremins_iphone
      - device_tracker.hue_keenetic_s
    tolerance: 50
  facebook_london:
    zone: facebook_london
    devices:
      - device_tracker.vladimir_eremins_iphone
    tolerance: 50

#device_sun_light_trigger:
#  light_group: group.all_lights
#  light_profile: reading
#  device_group: group.presence

timer:
  alarm_clock:
    duration: '07:30:00'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
