esphomeyaml:
  name: heater
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 100
    then:
      - switch.turn_off: heater

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.237
    subnet: 255.255.255.0
    gateway: 192.168.1.1
    dns1: 192.168.1.1
    dns2: 8.8.8.8

ota:
  password: !secret ota

logger:
  baud_rate: 115200

status_led:
  pin:
    number: GPIO2
    inverted: True

output:
  - platform: gpio
    id: gpio_led
    pin:
      number: GPIO2
      inverted: True

switch:
  - platform: gpio
    id: heater
    name: Heater
    icon: "mdi:temperature-celsius"
    pin:
      number: GPIO0
      inverted: True

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/London

mqtt:
  broker: 192.168.1.110
  port: 1883
  username: homeassistant
  password: !secret mosquitto

sensor:
  - platform: wifi_signal
    name: "Heater WiFi Signal Sensor"
    on_value:
      then:
        - output.turn_on: gpio_led
        - delay: 0.1s
        - output.turn_off: gpio_led
    update_interval: 5s
    expire_after: 120s
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          send_every: 6
          window_size: 12
