esphomeyaml:
  name: heater
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 100
    then:
      - switch.turn_off: heater

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.237
    subnet: 255.255.255.0
    gateway: 192.168.1.1
    dns1: 192.168.1.110
    dns2: 192.168.1.1

mqtt:
  broker: "home.yottatsa.name"
  port: 8883
  username: homeassistant
  password: !secret mosquitto
  ssl_fingerprints: !secret mosquitto_ssl

logger:
  baud_rate: 115200

ota:
  password: !secret ota

status_led:
  pin:
    number: GPIO2
    inverted: True

switch:
  - platform: gpio
    id: heater
    icon: "mdi:temperature-celsius"
    name: Heater
    pin:
      number: GPIO0
      inverted: True

sensor:
  - platform: wifi_signal
    name: "Heater WiFi Signal Sensor"
    update_interval: 5s
    expire_after: 120s
    filters:
      - sliding_window_moving_average:
          send_every: 6
          window_size: 12
